# Generated by Django 5.0.3 on 2024-08-07 13:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="default_files/default_face.jpg",
                        upload_to="account_files/profile_photos/",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        default="default_files/default_face.jpg",
                        upload_to="account_files/profile_photos/",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
